/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jyct5VPKPFiM97kWoWCufE
// Component: YehJWz95nk8f

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { DataFetcher } from "@plasmicpkgs/plasmic-query";
import Modal from "../../Modal"; // plasmic-import: Mf-_WMZkWbnX/component
import Button from "../../Button"; // plasmic-import: oq9TjOPy9RdD/component
import Switch from "../../Switch"; // plasmic-import: sMyjcyQ3Te1J/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: jyct5VPKPFiM97kWoWCufE/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: jyct5VPKPFiM97kWoWCufE/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: jyct5VPKPFiM97kWoWCufE/projectcss
import sty from "./PlasmicSettingNotification.module.css"; // plasmic-import: YehJWz95nk8f/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: EKG07ywqcyGB/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: ATfGBghsq52K/icon

createPlasmicElementProxy;

export type PlasmicSettingNotification__VariantMembers = {};
export type PlasmicSettingNotification__VariantsArgs = {};
type VariantPropType = keyof PlasmicSettingNotification__VariantsArgs;
export const PlasmicSettingNotification__VariantProps =
  new Array<VariantPropType>();

export type PlasmicSettingNotification__ArgsType = {};
type ArgPropType = keyof PlasmicSettingNotification__ArgsType;
export const PlasmicSettingNotification__ArgProps = new Array<ArgPropType>();

export type PlasmicSettingNotification__OverridesType = {
  root?: Flex__<"div">;
  httpRestApiFetcher?: Flex__<typeof DataFetcher>;
  dontHave2?: Flex__<typeof Modal>;
  header?: Flex__<"div">;
  igAndT?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  dontHave?: Flex__<"h3">;
  des?: Flex__<"div">;
  footer?: Flex__<"div">;
  up?: Flex__<"div">;
  right4?: Flex__<"div">;
  telegram?: Flex__<"div">;
  left4?: Flex__<"div">;
  bale?: Flex__<"div">;
  down?: Flex__<"div">;
  button?: Flex__<typeof Button>;
  دکمهرزروسایت?: Flex__<"div">;
  top?: Flex__<"div">;
  right?: Flex__<"div">;
  title?: Flex__<"div">;
  left?: Flex__<"div">;
  دکمهیرزروسایت?: Flex__<typeof Switch>;
  details?: Flex__<"div">;
  تسویه?: Flex__<"div">;
  تسویه2?: Flex__<"div">;
  تسویه4?: Flex__<"div">;
  دکمهرزرودستی?: Flex__<"div">;
  top2?: Flex__<"div">;
  right2?: Flex__<"div">;
  title2?: Flex__<"div">;
  left2?: Flex__<"div">;
  دکمهیرزروسایت2?: Flex__<typeof Switch>;
  details2?: Flex__<"div">;
  رزروجدید2?: Flex__<"div">;
  رزروجدید4?: Flex__<"div">;
  دکمهروزورودمهمان?: Flex__<"div">;
  top3?: Flex__<"div">;
  right3?: Flex__<"div">;
  title3?: Flex__<"div">;
  left3?: Flex__<"div">;
  دکمهیرزروسایت3?: Flex__<typeof Switch>;
  details3?: Flex__<"div">;
  رزروجدید3?: Flex__<"div">;
  رزروجدید5?: Flex__<"div">;
};

export interface DefaultSettingNotificationProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSettingNotification__RenderFunc(props: {
  variants: PlasmicSettingNotification__VariantsArgs;
  args: PlasmicSettingNotification__ArgsType;
  overrides: PlasmicSettingNotification__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const $globalActions = useGlobalActions?.();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "dontHave2.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return (() => {
                const isSign = $ctx.fetchedData?.[0]?.is_sign ?? false;
                return isSign;
              })();
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return false;
              }
              throw e;
            }
          })()
      },
      {
        path: "دکمهیرزروسایت.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          hasVariant(globalVariants, "screen", "mobileOnly")
            ? (() => {
                try {
                  return (() => {
                    let a = $ctx.fetchedData.filter(
                      item => item.feature_id == 1 && item.sources == 2
                    );
                    return a[0].is_active;
                  })();
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return false;
                  }
                  throw e;
                }
              })()
            : (() => {
                try {
                  return (() => {
                    let a = $ctx.fetchedData.filter(
                      item => item.feature_id == 1 && item.sources == 2
                    );
                    return a[0].is_active;
                  })();
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return false;
                  }
                  throw e;
                }
              })()
      },
      {
        path: "دکمهیرزروسایت2.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          hasVariant(globalVariants, "screen", "mobileOnly")
            ? (() => {
                try {
                  return (() => {
                    let a = $ctx.fetchedData.filter(
                      item => item.feature_id == 1 && item.sources == 2
                    );
                    return a[0].is_active;
                  })();
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return false;
                  }
                  throw e;
                }
              })()
            : (() => {
                try {
                  return (() => {
                    let a = $ctx.fetchedData.filter(
                      item => item.feature_id == 1 && item.sources == 1
                    );
                    return a[0].is_active;
                  })();
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return false;
                  }
                  throw e;
                }
              })()
      },
      {
        path: "دکمهیرزروسایت3.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          hasVariant(globalVariants, "screen", "mobileOnly")
            ? (() => {
                try {
                  return (() => {
                    let a = $ctx.fetchedData.filter(
                      item => item.feature_id == 1 && item.sources == 2
                    );
                    return a[0].is_active;
                  })();
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return false;
                  }
                  throw e;
                }
              })()
            : (() => {
                try {
                  return (() => {
                    let a = $ctx.fetchedData.filter(
                      item => item.feature_id == 4 && item.sources == 1
                    );
                    return a[0].is_active;
                  })();
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return false;
                  }
                  throw e;
                }
              })()
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__tCn32)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__cs6Ie
              )}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {
                    "\u062a\u0646\u0638\u06cc\u0645 \u0627\u0639\u0644\u0627\u0646\u0627\u062a"
                  }
                </span>
              </React.Fragment>
            </div>
            <DataFetcher
              data-plasmic-name={"httpRestApiFetcher"}
              data-plasmic-override={overrides.httpRestApiFetcher}
              className={classNames("__wab_instance", sty.httpRestApiFetcher)}
              dataName={"fetchedData"}
              errorDisplay={
                <DataCtxReader__>
                  {$ctx => "Error fetching data"}
                </DataCtxReader__>
              }
              errorName={"fetchError"}
              headers={(() => {
                try {
                  return fetch(
                    "https://second-n8n.darkube.app/webhook/plasmic",
                    {
                      method: "GET", // یا POST
                      credentials: "include" // مهم: این باعث میشه کوکی هم فرستاده بشه
                    }
                  );
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()}
              loadingDisplay={null}
              method={"GET"}
              noLayout={false}
              previewSpinner={false}
              url={"https://second-n8n.darkube.app/webhook/plasmic"}
            >
              <DataCtxReader__>
                {$ctx => (
                  <React.Fragment>
                    {(() => {
                      const child$Props = {
                        className: classNames("__wab_instance", sty.dontHave2),
                        closeOnBackdropClick: false,
                        content: (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__f05H5
                            )}
                          >
                            <div
                              data-plasmic-name={"des"}
                              data-plasmic-override={overrides.des}
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.des,
                                "rtl"
                              )}
                            >
                              {
                                "\u0627\u0628\u062a\u062f\u0627 \u0628\u0627\u06cc\u062f \u0631\u0628\u0627\u062a \u0645\u06cc\u0627\u0646 \u0631\u0627 \u062b\u0628\u062a\u200c\u0646\u0627\u0645 \u06a9\u0646\u06cc\u062f.\n\n\u0627\u06cc\u0646 \u0631\u0628\u0627\u062a \u0647\u0645\u0647 \u0631\u0632\u0631\u0648\u0647\u0627\u06cc \u0633\u0627\u06cc\u062a\u200c\u0647\u0627\u06cc\u06cc \u0645\u062b\u0644 \u062c\u0627\u0628\u0627\u0645\u0627 \u0648 \u0627\u062a\u0627\u0642\u06a9 \u0648 ... \u0631\u0627 \u0647\u0645\u0627\u0646 \u0644\u062d\u0638\u0647 \u0628\u0627 \u062c\u0632\u0626\u06cc\u0627\u062a \u0628\u0631\u0627\u062a\u0648\u0646 \u0645\u06cc\u200c\u0641\u0631\u0633\u062a\u0647\u060c \u062d\u062a\u06cc \u0631\u0632\u0631\u0648\u0647\u0627\u06cc \u062f\u0633\u062a\u06cc \u0648 \u0631\u0648\u0632 \u0648\u0631\u0648\u062f \u0645\u0647\u0645\u0627\u0646 \u0631\u0648 \u0647\u0645 \u06cc\u0627\u062f\u0622\u0648\u0631\u06cc \u0645\u06cc\u200c\u06a9\u0646\u0647.\n\n\u062f\u0631 \u0627\u06cc\u0646 \u0635\u0641\u062d\u0647 \u0645\u06cc\u200c\u062a\u0648\u0627\u0646\u06cc\u062f \u0645\u0634\u062e\u0635 \u06a9\u0646\u06cc\u062f \u0686\u0647 \u0627\u0639\u0644\u0627\u0646\u0627\u062a\u06cc \u0645\u06cc\u200c\u062e\u0648\u0627\u0647\u06cc\u062f \u062f\u0631\u06cc\u0627\u0641\u062a \u06a9\u0646\u06cc\u062f."
                              }
                            </div>
                          </div>
                        ),
                        footer: (
                          <div
                            data-plasmic-name={"footer"}
                            data-plasmic-override={overrides.footer}
                            className={classNames(projectcss.all, sty.footer)}
                          >
                            <div
                              data-plasmic-name={"up"}
                              data-plasmic-override={overrides.up}
                              className={classNames(projectcss.all, sty.up)}
                            >
                              <div
                                data-plasmic-name={"right4"}
                                data-plasmic-override={overrides.right4}
                                className={classNames(
                                  projectcss.all,
                                  sty.right4
                                )}
                              >
                                <div
                                  data-plasmic-name={"telegram"}
                                  data-plasmic-override={overrides.telegram}
                                  className={classNames(
                                    projectcss.all,
                                    sty.telegram
                                  )}
                                  onClick={async event => {
                                    const $steps = {};

                                    $steps["runCode"] = true
                                      ? (() => {
                                          const actionArgs = {
                                            customFunction: async () => {
                                              return (() => {
                                                return (window.location.href =
                                                  "https://t.me/rentamon_notification_bot");
                                              })();
                                            }
                                          };
                                          return (({ customFunction }) => {
                                            return customFunction();
                                          })?.apply(null, [actionArgs]);
                                        })()
                                      : undefined;
                                    if (
                                      $steps["runCode"] != null &&
                                      typeof $steps["runCode"] === "object" &&
                                      typeof $steps["runCode"].then ===
                                        "function"
                                    ) {
                                      $steps["runCode"] =
                                        await $steps["runCode"];
                                    }
                                  }}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__lhbZj
                                    )}
                                  >
                                    {"\u062a\u0644\u06af\u0631\u0627\u0645"}
                                  </div>
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"left4"}
                                data-plasmic-override={overrides.left4}
                                className={classNames(
                                  projectcss.all,
                                  sty.left4
                                )}
                              >
                                <div
                                  data-plasmic-name={"bale"}
                                  data-plasmic-override={overrides.bale}
                                  className={classNames(
                                    projectcss.all,
                                    sty.bale
                                  )}
                                  onClick={async event => {
                                    const $steps = {};

                                    $steps["runCode"] = true
                                      ? (() => {
                                          const actionArgs = {
                                            customFunction: async () => {
                                              return (() => {
                                                return (window.location.href =
                                                  "https://ble.ir/rentamonbot");
                                              })();
                                            }
                                          };
                                          return (({ customFunction }) => {
                                            return customFunction();
                                          })?.apply(null, [actionArgs]);
                                        })()
                                      : undefined;
                                    if (
                                      $steps["runCode"] != null &&
                                      typeof $steps["runCode"] === "object" &&
                                      typeof $steps["runCode"].then ===
                                        "function"
                                    ) {
                                      $steps["runCode"] =
                                        await $steps["runCode"];
                                    }
                                  }}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__iBg3P
                                    )}
                                  >
                                    {"\u0628\u0644\u0647"}
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"down"}
                              data-plasmic-override={overrides.down}
                              className={classNames(projectcss.all, sty.down)}
                            >
                              <Button
                                data-plasmic-name={"button"}
                                data-plasmic-override={overrides.button}
                                className={classNames(
                                  "__wab_instance",
                                  sty.button
                                )}
                                label={
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text___10Sm8
                                    )}
                                  >
                                    {"\u0628\u0627\u0632\u06af\u0634\u062a"}
                                  </div>
                                }
                                onClick={async event => {
                                  const $steps = {};

                                  $steps["updateAriaDialogTriggerIsOpen"] = true
                                    ? (() => {
                                        const actionArgs = {
                                          variable: {
                                            objRoot: $state,
                                            variablePath: [
                                              "ariaDialogTrigger",
                                              "isOpen"
                                            ]
                                          },
                                          operation: 0,
                                          value: false
                                        };
                                        return (({
                                          variable,
                                          value,
                                          startIndex,
                                          deleteCount
                                        }) => {
                                          if (!variable) {
                                            return;
                                          }
                                          const { objRoot, variablePath } =
                                            variable;

                                          $stateSet(
                                            objRoot,
                                            variablePath,
                                            value
                                          );
                                          return value;
                                        })?.apply(null, [actionArgs]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps["updateAriaDialogTriggerIsOpen"] !=
                                      null &&
                                    typeof $steps[
                                      "updateAriaDialogTriggerIsOpen"
                                    ] === "object" &&
                                    typeof $steps[
                                      "updateAriaDialogTriggerIsOpen"
                                    ].then === "function"
                                  ) {
                                    $steps["updateAriaDialogTriggerIsOpen"] =
                                      await $steps[
                                        "updateAriaDialogTriggerIsOpen"
                                      ];
                                  }
                                }}
                                openLinkInNewTab={false}
                                type={"soft"}
                              />
                            </div>
                          </div>
                        ),
                        heading: (
                          <div
                            data-plasmic-name={"header"}
                            data-plasmic-override={overrides.header}
                            className={classNames(projectcss.all, sty.header)}
                          >
                            <div
                              data-plasmic-name={"igAndT"}
                              data-plasmic-override={overrides.igAndT}
                              className={classNames(projectcss.all, sty.igAndT)}
                            >
                              <PlasmicImg__
                                data-plasmic-name={"img"}
                                data-plasmic-override={overrides.img}
                                alt={""}
                                className={classNames(sty.img)}
                                displayHeight={"146px"}
                                displayMaxHeight={"none"}
                                displayMaxWidth={"100%"}
                                displayMinHeight={"0"}
                                displayMinWidth={"0"}
                                displayWidth={"auto"}
                                loading={"lazy"}
                                src={{
                                  src: "/plasmic/notification_setting/images/logoAutomationJpg.jpg",
                                  fullWidth: 1024,
                                  fullHeight: 1024,
                                  aspectRatio: undefined
                                }}
                              />

                              <h3
                                data-plasmic-name={"dontHave"}
                                data-plasmic-override={overrides.dontHave}
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.dontHave,
                                  "rtl"
                                )}
                              >
                                {
                                  "\u0634\u0645\u0627 \u0631\u0628\u0627\u062a \u0627\u0637\u0644\u0627\u0639\u200c\u0631\u0633\u0627\u0646\u06cc \u0645\u06cc\u0627\u0646 \u0631\u0648 \u0646\u062f\u0627\u0631\u06cc\u0646."
                                }
                              </h3>
                            </div>
                          </div>
                        ),
                        isOpen: generateStateValueProp($state, [
                          "dontHave2",
                          "isOpen"
                        ]),
                        noTrigger: undefined,
                        onOpenChange: async (...eventArgs: any) => {
                          generateStateOnChangeProp($state, [
                            "dontHave2",
                            "isOpen"
                          ]).apply(null, eventArgs);

                          if (
                            eventArgs.length > 1 &&
                            eventArgs[1] &&
                            eventArgs[1]._plasmic_state_init_
                          ) {
                            return;
                          }
                        },
                        trigger: null
                      };

                      initializePlasmicStates(
                        $state,
                        [
                          {
                            name: "dontHave2.isOpen",
                            initFunc: ({ $props, $state, $queries }) =>
                              (() => {
                                try {
                                  return (() => {
                                    const isSign =
                                      $ctx.fetchedData?.[0]?.is_sign ?? false;
                                    return isSign;
                                  })();
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return false;
                                  }
                                  throw e;
                                }
                              })()
                          }
                        ],
                        []
                      );
                      return (
                        <Modal
                          data-plasmic-name={"dontHave2"}
                          data-plasmic-override={overrides.dontHave2}
                          {...child$Props}
                        />
                      );
                    })()}
                    <div
                      data-plasmic-name={
                        "\u062f\u06a9\u0645\u0647\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a"
                      }
                      data-plasmic-override={overrides.دکمهرزروسایت}
                      className={classNames(projectcss.all, sty.دکمهرزروسایت)}
                    >
                      <div
                        data-plasmic-name={"top"}
                        data-plasmic-override={overrides.top}
                        className={classNames(projectcss.all, sty.top)}
                      >
                        <div
                          data-plasmic-name={"right"}
                          data-plasmic-override={overrides.right}
                          className={classNames(projectcss.all, sty.right)}
                        >
                          <div
                            data-plasmic-name={"title"}
                            data-plasmic-override={overrides.title}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.title
                            )}
                          >
                            {
                              "\u0627\u0639\u0644\u0627\u0646\u0627\u062a \u0631\u0632\u0631\u0648 \u0633\u0627\u06cc\u062a"
                            }
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"left"}
                          data-plasmic-override={overrides.left}
                          className={classNames(
                            projectcss.all,
                            sty.left,
                            "ltr2"
                          )}
                        >
                          {(() => {
                            const child$Props = {
                              className: classNames(
                                "__wab_instance",
                                sty.دکمهیرزروسایت
                              ),
                              isSelected: generateStateValueProp($state, [
                                "دکمهیرزروسایت",
                                "isSelected"
                              ]),
                              label: null,
                              onChange: async (...eventArgs: any) => {
                                generateStateOnChangeProp($state, [
                                  "دکمهیرزروسایت",
                                  "isSelected"
                                ]).apply(null, eventArgs);

                                if (
                                  eventArgs.length > 1 &&
                                  eventArgs[1] &&
                                  eventArgs[1]._plasmic_state_init_
                                ) {
                                  return;
                                }

                                (async val => {
                                  const $steps = {};

                                  $steps["invokeGlobalAction"] = true
                                    ? (() => {
                                        const actionArgs = {
                                          args: [
                                            "success",
                                            (() => {
                                              try {
                                                return $state["دکمهیرزروسایت"]
                                                  .isSelected
                                                  ? "اعلانات رزرو سایت روشن شد"
                                                  : "اعلانات رزرو سایت خاموش شد";
                                              } catch (e) {
                                                if (
                                                  e instanceof TypeError ||
                                                  e?.plasmicType ===
                                                    "PlasmicUndefinedDataError"
                                                ) {
                                                  return undefined;
                                                }
                                                throw e;
                                              }
                                            })(),
                                            ``,
                                            undefined,
                                            "top"
                                          ]
                                        };
                                        return $globalActions[
                                          "plasmic-antd5-config-provider.showNotification"
                                        ]?.apply(null, [...actionArgs.args]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps["invokeGlobalAction"] != null &&
                                    typeof $steps["invokeGlobalAction"] ===
                                      "object" &&
                                    typeof $steps["invokeGlobalAction"].then ===
                                      "function"
                                  ) {
                                    $steps["invokeGlobalAction"] =
                                      await $steps["invokeGlobalAction"];
                                  }

                                  $steps["runCode"] = true
                                    ? (() => {
                                        const actionArgs = {
                                          customFunction: async () => {
                                            return (async () => {
                                              const item =
                                                $ctx.fetchedData.find(
                                                  i =>
                                                    i.feature_id == 1 &&
                                                    i.sources == 2
                                                );
                                              if (item) {
                                                const newValue = event;
                                                return await fetch(
                                                  "https://second-n8n.darkube.app/webhook/update/plasmic",
                                                  {
                                                    method: "POST",
                                                    headers: {
                                                      "Content-Type":
                                                        "application/json"
                                                    },
                                                    body: JSON.stringify({
                                                      user_id: item.user_id,
                                                      feature_id:
                                                        item.feature_id,
                                                      sources: item.sources,
                                                      is_active:
                                                        $state.دکمهیرزروسایت
                                                          .isSelected,
                                                      website: 1
                                                    })
                                                  }
                                                );
                                              }
                                            })();
                                          }
                                        };
                                        return (({ customFunction }) => {
                                          return customFunction();
                                        })?.apply(null, [actionArgs]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps["runCode"] != null &&
                                    typeof $steps["runCode"] === "object" &&
                                    typeof $steps["runCode"].then === "function"
                                  ) {
                                    $steps["runCode"] = await $steps["runCode"];
                                  }
                                }).apply(null, eventArgs);
                              }
                            };

                            initializePlasmicStates(
                              $state,
                              [
                                {
                                  name: "دکمهیرزروسایت.isSelected",
                                  initFunc: ({ $props, $state, $queries }) =>
                                    hasVariant(
                                      globalVariants,
                                      "screen",
                                      "mobileOnly"
                                    )
                                      ? (() => {
                                          try {
                                            return (() => {
                                              let a = $ctx.fetchedData.filter(
                                                item =>
                                                  item.feature_id == 1 &&
                                                  item.sources == 2
                                              );
                                              return a[0].is_active;
                                            })();
                                          } catch (e) {
                                            if (
                                              e instanceof TypeError ||
                                              e?.plasmicType ===
                                                "PlasmicUndefinedDataError"
                                            ) {
                                              return false;
                                            }
                                            throw e;
                                          }
                                        })()
                                      : (() => {
                                          try {
                                            return (() => {
                                              let a = $ctx.fetchedData.filter(
                                                item =>
                                                  item.feature_id == 1 &&
                                                  item.sources == 2
                                              );
                                              return a[0].is_active;
                                            })();
                                          } catch (e) {
                                            if (
                                              e instanceof TypeError ||
                                              e?.plasmicType ===
                                                "PlasmicUndefinedDataError"
                                            ) {
                                              return false;
                                            }
                                            throw e;
                                          }
                                        })()
                                }
                              ],
                              []
                            );
                            return (
                              <Switch
                                data-plasmic-name={
                                  "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a"
                                }
                                data-plasmic-override={overrides.دکمهیرزروسایت}
                                {...child$Props}
                              />
                            );
                          })()}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"details"}
                        data-plasmic-override={overrides.details}
                        className={classNames(projectcss.all, sty.details)}
                      >
                        <div
                          data-plasmic-name={"\u062a\u0633\u0648\u06cc\u0647"}
                          data-plasmic-override={overrides.تسویه}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.تسویه,
                            "rtl"
                          )}
                        >
                          {
                            "- \u062f\u0631\u06cc\u0627\u0641\u062a \u0631\u0632\u0631\u0648 \u062c\u062f\u06cc\u062f"
                          }
                        </div>
                        <div
                          data-plasmic-name={"\u062a\u0633\u0648\u06cc\u06472"}
                          data-plasmic-override={overrides.تسویه2}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.تسویه2,
                            "rtl"
                          )}
                        >
                          {
                            "- \u0627\u0639\u0644\u0627\u0645 \u06a9\u0646\u0633\u0644\u06cc"
                          }
                        </div>
                        <div
                          data-plasmic-name={"\u062a\u0633\u0648\u06cc\u06474"}
                          data-plasmic-override={overrides.تسویه4}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.تسویه4,
                            "rtl"
                          )}
                        >
                          {
                            "- \u0627\u0639\u0644\u0627\u0645 \u062a\u0633\u0648\u06cc\u0647"
                          }
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={
                        "\u062f\u06a9\u0645\u0647\u0631\u0632\u0631\u0648\u062f\u0633\u062a\u06cc"
                      }
                      data-plasmic-override={overrides.دکمهرزرودستی}
                      className={classNames(projectcss.all, sty.دکمهرزرودستی)}
                    >
                      <div
                        data-plasmic-name={"top2"}
                        data-plasmic-override={overrides.top2}
                        className={classNames(projectcss.all, sty.top2)}
                      >
                        <div
                          data-plasmic-name={"right2"}
                          data-plasmic-override={overrides.right2}
                          className={classNames(projectcss.all, sty.right2)}
                        >
                          <div
                            data-plasmic-name={"title2"}
                            data-plasmic-override={overrides.title2}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.title2
                            )}
                          >
                            {hasVariant(
                              globalVariants,
                              "screen",
                              "mobileOnly"
                            ) ? (
                              <React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ fontWeight: 700 }}
                                >
                                  {
                                    "\u0627\u0639\u0644\u0627\u0646\u0627\u062a \u0631\u0632\u0631\u0648 \u062f\u0633\u062a\u06cc"
                                  }
                                </span>
                              </React.Fragment>
                            ) : (
                              <React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ fontWeight: 700 }}
                                >
                                  {
                                    "\u0627\u0639\u0644\u0627\u0646\u0627\u062a \u0631\u0632\u0631\u0648 \u062f\u0633\u062a\u06cc"
                                  }
                                </span>
                              </React.Fragment>
                            )}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"left2"}
                          data-plasmic-override={overrides.left2}
                          className={classNames(
                            projectcss.all,
                            sty.left2,
                            "ltr2"
                          )}
                        >
                          {(() => {
                            const child$Props = {
                              className: classNames(
                                "__wab_instance",
                                sty.دکمهیرزروسایت2
                              ),
                              isSelected: generateStateValueProp($state, [
                                "دکمهیرزروسایت2",
                                "isSelected"
                              ]),
                              label: null,
                              onChange: async (...eventArgs: any) => {
                                generateStateOnChangeProp($state, [
                                  "دکمهیرزروسایت2",
                                  "isSelected"
                                ]).apply(null, eventArgs);

                                if (
                                  eventArgs.length > 1 &&
                                  eventArgs[1] &&
                                  eventArgs[1]._plasmic_state_init_
                                ) {
                                  return;
                                }

                                (async val => {
                                  const $steps = {};

                                  $steps["invokeGlobalAction"] = true
                                    ? (() => {
                                        const actionArgs = {
                                          args: [
                                            "success",
                                            (() => {
                                              try {
                                                return $state["دکمهیرزروسایت2"]
                                                  .isSelected
                                                  ? "اعلانات رزرو دستی روشن شد"
                                                  : "اعلانات رزرو دستی خاموش شد";
                                              } catch (e) {
                                                if (
                                                  e instanceof TypeError ||
                                                  e?.plasmicType ===
                                                    "PlasmicUndefinedDataError"
                                                ) {
                                                  return undefined;
                                                }
                                                throw e;
                                              }
                                            })(),
                                            ``,
                                            undefined,
                                            "top"
                                          ]
                                        };
                                        return $globalActions[
                                          "plasmic-antd5-config-provider.showNotification"
                                        ]?.apply(null, [...actionArgs.args]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps["invokeGlobalAction"] != null &&
                                    typeof $steps["invokeGlobalAction"] ===
                                      "object" &&
                                    typeof $steps["invokeGlobalAction"].then ===
                                      "function"
                                  ) {
                                    $steps["invokeGlobalAction"] =
                                      await $steps["invokeGlobalAction"];
                                  }

                                  $steps["runCode"] = true
                                    ? (() => {
                                        const actionArgs = {
                                          customFunction: async () => {
                                            return (async () => {
                                              const item =
                                                $ctx.fetchedData.find(
                                                  i =>
                                                    i.feature_id == 1 &&
                                                    i.sources == 1
                                                );
                                              if (item) {
                                                const newValue = event;
                                                return await fetch(
                                                  "https://second-n8n.darkube.app/webhook/update/plasmic",
                                                  {
                                                    method: "POST",
                                                    headers: {
                                                      "Content-Type":
                                                        "application/json"
                                                    },
                                                    body: JSON.stringify({
                                                      user_id: item.user_id,
                                                      feature_id:
                                                        item.feature_id,
                                                      sources: item.sources,
                                                      is_active:
                                                        $state["دکمهیرزروسایت2"]
                                                          .isSelected,
                                                      website: 2
                                                    })
                                                  }
                                                );
                                              }
                                            })();
                                          }
                                        };
                                        return (({ customFunction }) => {
                                          return customFunction();
                                        })?.apply(null, [actionArgs]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps["runCode"] != null &&
                                    typeof $steps["runCode"] === "object" &&
                                    typeof $steps["runCode"].then === "function"
                                  ) {
                                    $steps["runCode"] = await $steps["runCode"];
                                  }
                                }).apply(null, eventArgs);
                              }
                            };

                            initializePlasmicStates(
                              $state,
                              [
                                {
                                  name: "دکمهیرزروسایت2.isSelected",
                                  initFunc: ({ $props, $state, $queries }) =>
                                    hasVariant(
                                      globalVariants,
                                      "screen",
                                      "mobileOnly"
                                    )
                                      ? (() => {
                                          try {
                                            return (() => {
                                              let a = $ctx.fetchedData.filter(
                                                item =>
                                                  item.feature_id == 1 &&
                                                  item.sources == 2
                                              );
                                              return a[0].is_active;
                                            })();
                                          } catch (e) {
                                            if (
                                              e instanceof TypeError ||
                                              e?.plasmicType ===
                                                "PlasmicUndefinedDataError"
                                            ) {
                                              return false;
                                            }
                                            throw e;
                                          }
                                        })()
                                      : (() => {
                                          try {
                                            return (() => {
                                              let a = $ctx.fetchedData.filter(
                                                item =>
                                                  item.feature_id == 1 &&
                                                  item.sources == 1
                                              );
                                              return a[0].is_active;
                                            })();
                                          } catch (e) {
                                            if (
                                              e instanceof TypeError ||
                                              e?.plasmicType ===
                                                "PlasmicUndefinedDataError"
                                            ) {
                                              return false;
                                            }
                                            throw e;
                                          }
                                        })()
                                }
                              ],
                              []
                            );
                            return (
                              <Switch
                                data-plasmic-name={
                                  "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a2"
                                }
                                data-plasmic-override={overrides.دکمهیرزروسایت2}
                                {...child$Props}
                              />
                            );
                          })()}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"details2"}
                        data-plasmic-override={overrides.details2}
                        className={classNames(projectcss.all, sty.details2)}
                      >
                        <div
                          data-plasmic-name={
                            "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f2"
                          }
                          data-plasmic-override={overrides.رزروجدید2}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.رزروجدید2,
                            "rtl"
                          )}
                        >
                          {
                            "- \u062f\u0631\u06cc\u0627\u0641\u062a \u0631\u0632\u0631\u0648 \u062c\u062f\u06cc\u062f"
                          }
                        </div>
                        <div
                          data-plasmic-name={
                            "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f4"
                          }
                          data-plasmic-override={overrides.رزروجدید4}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.رزروجدید4,
                            "rtl"
                          )}
                        >
                          {
                            "- \u0627\u0639\u0644\u0627\u0645 \u06a9\u0646\u0633\u0644\u06cc"
                          }
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={
                        "\u062f\u06a9\u0645\u0647\u0631\u0648\u0632\u0648\u0631\u0648\u062f\u0645\u0647\u0645\u0627\u0646"
                      }
                      data-plasmic-override={overrides.دکمهروزورودمهمان}
                      className={classNames(
                        projectcss.all,
                        sty.دکمهروزورودمهمان
                      )}
                    >
                      <div
                        data-plasmic-name={"top3"}
                        data-plasmic-override={overrides.top3}
                        className={classNames(projectcss.all, sty.top3)}
                      >
                        <div
                          data-plasmic-name={"right3"}
                          data-plasmic-override={overrides.right3}
                          className={classNames(projectcss.all, sty.right3)}
                        >
                          <div
                            data-plasmic-name={"title3"}
                            data-plasmic-override={overrides.title3}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.title3
                            )}
                          >
                            {hasVariant(
                              globalVariants,
                              "screen",
                              "mobileOnly"
                            ) ? (
                              <React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ fontWeight: 700 }}
                                >
                                  {
                                    "\u0627\u0639\u0644\u0627\u0646\u0627\u062a \u0631\u0648\u0632 \u0648\u0631\u0648\u062f \u0645\u0647\u0645\u0627\u0646"
                                  }
                                </span>
                              </React.Fragment>
                            ) : (
                              <React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ fontWeight: 700 }}
                                >
                                  {
                                    "\u0627\u0639\u0644\u0627\u0646\u0627\u062a \u0631\u0648\u0632 \u0648\u0631\u0648\u062f \u0645\u0647\u0645\u0627\u0646"
                                  }
                                </span>
                              </React.Fragment>
                            )}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"left3"}
                          data-plasmic-override={overrides.left3}
                          className={classNames(
                            projectcss.all,
                            sty.left3,
                            "ltr2"
                          )}
                        >
                          {(() => {
                            const child$Props = {
                              className: classNames(
                                "__wab_instance",
                                sty.دکمهیرزروسایت3
                              ),
                              isSelected: generateStateValueProp($state, [
                                "دکمهیرزروسایت3",
                                "isSelected"
                              ]),
                              label: null,
                              onChange: async (...eventArgs: any) => {
                                generateStateOnChangeProp($state, [
                                  "دکمهیرزروسایت3",
                                  "isSelected"
                                ]).apply(null, eventArgs);

                                if (
                                  eventArgs.length > 1 &&
                                  eventArgs[1] &&
                                  eventArgs[1]._plasmic_state_init_
                                ) {
                                  return;
                                }

                                (async val => {
                                  const $steps = {};

                                  $steps["invokeGlobalAction"] = true
                                    ? (() => {
                                        const actionArgs = {
                                          args: [
                                            "success",
                                            (() => {
                                              try {
                                                return $state["دکمهیرزروسایت3"]
                                                  .isSelected
                                                  ? "اعلانات روز ورود مهمان روشن شد"
                                                  : "اعلانات روز ورود مهمان خاموش شد";
                                              } catch (e) {
                                                if (
                                                  e instanceof TypeError ||
                                                  e?.plasmicType ===
                                                    "PlasmicUndefinedDataError"
                                                ) {
                                                  return undefined;
                                                }
                                                throw e;
                                              }
                                            })(),
                                            ``,
                                            undefined,
                                            "top"
                                          ]
                                        };
                                        return $globalActions[
                                          "plasmic-antd5-config-provider.showNotification"
                                        ]?.apply(null, [...actionArgs.args]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps["invokeGlobalAction"] != null &&
                                    typeof $steps["invokeGlobalAction"] ===
                                      "object" &&
                                    typeof $steps["invokeGlobalAction"].then ===
                                      "function"
                                  ) {
                                    $steps["invokeGlobalAction"] =
                                      await $steps["invokeGlobalAction"];
                                  }

                                  $steps["runCode"] = true
                                    ? (() => {
                                        const actionArgs = {
                                          customFunction: async () => {
                                            return (async () => {
                                              const item =
                                                $ctx.fetchedData.find(
                                                  i =>
                                                    i.feature_id == 4 &&
                                                    i.sources == 1
                                                );
                                              if (item) {
                                                const newValue = event;
                                                return await fetch(
                                                  "https://second-n8n.darkube.app/webhook/update/plasmic",
                                                  {
                                                    method: "POST",
                                                    headers: {
                                                      "Content-Type":
                                                        "application/json"
                                                    },
                                                    body: JSON.stringify({
                                                      user_id: item.user_id,
                                                      feature_id:
                                                        item.feature_id,
                                                      sources: item.sources,
                                                      is_active:
                                                        $state["دکمهیرزروسایت3"]
                                                          .isSelected,
                                                      website: 3
                                                    })
                                                  }
                                                );
                                              }
                                            })();
                                          }
                                        };
                                        return (({ customFunction }) => {
                                          return customFunction();
                                        })?.apply(null, [actionArgs]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps["runCode"] != null &&
                                    typeof $steps["runCode"] === "object" &&
                                    typeof $steps["runCode"].then === "function"
                                  ) {
                                    $steps["runCode"] = await $steps["runCode"];
                                  }
                                }).apply(null, eventArgs);
                              }
                            };

                            initializePlasmicStates(
                              $state,
                              [
                                {
                                  name: "دکمهیرزروسایت3.isSelected",
                                  initFunc: ({ $props, $state, $queries }) =>
                                    hasVariant(
                                      globalVariants,
                                      "screen",
                                      "mobileOnly"
                                    )
                                      ? (() => {
                                          try {
                                            return (() => {
                                              let a = $ctx.fetchedData.filter(
                                                item =>
                                                  item.feature_id == 1 &&
                                                  item.sources == 2
                                              );
                                              return a[0].is_active;
                                            })();
                                          } catch (e) {
                                            if (
                                              e instanceof TypeError ||
                                              e?.plasmicType ===
                                                "PlasmicUndefinedDataError"
                                            ) {
                                              return false;
                                            }
                                            throw e;
                                          }
                                        })()
                                      : (() => {
                                          try {
                                            return (() => {
                                              let a = $ctx.fetchedData.filter(
                                                item =>
                                                  item.feature_id == 4 &&
                                                  item.sources == 1
                                              );
                                              return a[0].is_active;
                                            })();
                                          } catch (e) {
                                            if (
                                              e instanceof TypeError ||
                                              e?.plasmicType ===
                                                "PlasmicUndefinedDataError"
                                            ) {
                                              return false;
                                            }
                                            throw e;
                                          }
                                        })()
                                }
                              ],
                              []
                            );
                            return (
                              <Switch
                                data-plasmic-name={
                                  "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a3"
                                }
                                data-plasmic-override={overrides.دکمهیرزروسایت3}
                                {...child$Props}
                              />
                            );
                          })()}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"details3"}
                        data-plasmic-override={overrides.details3}
                        className={classNames(projectcss.all, sty.details3)}
                      >
                        <div
                          data-plasmic-name={
                            "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f3"
                          }
                          data-plasmic-override={overrides.رزروجدید3}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.رزروجدید3,
                            "rtl"
                          )}
                        >
                          {
                            "- \u0631\u0648\u0632 \u0648\u0631\u0648\u062f \u0645\u0647\u0645\u0627\u0646 \u0633\u0627\u06cc\u062a"
                          }
                        </div>
                        <div
                          data-plasmic-name={
                            "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f5"
                          }
                          data-plasmic-override={overrides.رزروجدید5}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.رزروجدید5,
                            "rtl"
                          )}
                        >
                          {
                            "- \u0631\u0648\u0632 \u0648\u0631\u0648\u062f \u0645\u0647\u0645\u0627\u0646 \u062f\u0633\u062a\u06cc"
                          }
                        </div>
                      </div>
                    </div>
                  </React.Fragment>
                )}
              </DataCtxReader__>
            </DataFetcher>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "httpRestApiFetcher",
    "dontHave2",
    "header",
    "igAndT",
    "img",
    "dontHave",
    "des",
    "footer",
    "up",
    "right4",
    "telegram",
    "left4",
    "bale",
    "down",
    "button",
    "\u062f\u06a9\u0645\u0647\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a",
    "top",
    "right",
    "title",
    "left",
    "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a",
    "details",
    "\u062a\u0633\u0648\u06cc\u0647",
    "\u062a\u0633\u0648\u06cc\u06472",
    "\u062a\u0633\u0648\u06cc\u06474",
    "\u062f\u06a9\u0645\u0647\u0631\u0632\u0631\u0648\u062f\u0633\u062a\u06cc",
    "top2",
    "right2",
    "title2",
    "left2",
    "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a2",
    "details2",
    "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f2",
    "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f4",
    "\u062f\u06a9\u0645\u0647\u0631\u0648\u0632\u0648\u0631\u0648\u062f\u0645\u0647\u0645\u0627\u0646",
    "top3",
    "right3",
    "title3",
    "left3",
    "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a3",
    "details3",
    "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f3",
    "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f5"
  ],
  httpRestApiFetcher: [
    "httpRestApiFetcher",
    "dontHave2",
    "header",
    "igAndT",
    "img",
    "dontHave",
    "des",
    "footer",
    "up",
    "right4",
    "telegram",
    "left4",
    "bale",
    "down",
    "button",
    "\u062f\u06a9\u0645\u0647\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a",
    "top",
    "right",
    "title",
    "left",
    "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a",
    "details",
    "\u062a\u0633\u0648\u06cc\u0647",
    "\u062a\u0633\u0648\u06cc\u06472",
    "\u062a\u0633\u0648\u06cc\u06474",
    "\u062f\u06a9\u0645\u0647\u0631\u0632\u0631\u0648\u062f\u0633\u062a\u06cc",
    "top2",
    "right2",
    "title2",
    "left2",
    "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a2",
    "details2",
    "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f2",
    "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f4",
    "\u062f\u06a9\u0645\u0647\u0631\u0648\u0632\u0648\u0631\u0648\u062f\u0645\u0647\u0645\u0627\u0646",
    "top3",
    "right3",
    "title3",
    "left3",
    "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a3",
    "details3",
    "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f3",
    "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f5"
  ],
  dontHave2: [
    "dontHave2",
    "header",
    "igAndT",
    "img",
    "dontHave",
    "des",
    "footer",
    "up",
    "right4",
    "telegram",
    "left4",
    "bale",
    "down",
    "button"
  ],
  header: ["header", "igAndT", "img", "dontHave"],
  igAndT: ["igAndT", "img", "dontHave"],
  img: ["img"],
  dontHave: ["dontHave"],
  des: ["des"],
  footer: [
    "footer",
    "up",
    "right4",
    "telegram",
    "left4",
    "bale",
    "down",
    "button"
  ],
  up: ["up", "right4", "telegram", "left4", "bale"],
  right4: ["right4", "telegram"],
  telegram: ["telegram"],
  left4: ["left4", "bale"],
  bale: ["bale"],
  down: ["down", "button"],
  button: ["button"],
  دکمهرزروسایت: [
    "\u062f\u06a9\u0645\u0647\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a",
    "top",
    "right",
    "title",
    "left",
    "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a",
    "details",
    "\u062a\u0633\u0648\u06cc\u0647",
    "\u062a\u0633\u0648\u06cc\u06472",
    "\u062a\u0633\u0648\u06cc\u06474"
  ],
  top: [
    "top",
    "right",
    "title",
    "left",
    "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a"
  ],
  right: ["right", "title"],
  title: ["title"],
  left: [
    "left",
    "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a"
  ],
  دکمهیرزروسایت: [
    "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a"
  ],
  details: [
    "details",
    "\u062a\u0633\u0648\u06cc\u0647",
    "\u062a\u0633\u0648\u06cc\u06472",
    "\u062a\u0633\u0648\u06cc\u06474"
  ],
  تسویه: ["\u062a\u0633\u0648\u06cc\u0647"],
  تسویه2: ["\u062a\u0633\u0648\u06cc\u06472"],
  تسویه4: ["\u062a\u0633\u0648\u06cc\u06474"],
  دکمهرزرودستی: [
    "\u062f\u06a9\u0645\u0647\u0631\u0632\u0631\u0648\u062f\u0633\u062a\u06cc",
    "top2",
    "right2",
    "title2",
    "left2",
    "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a2",
    "details2",
    "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f2",
    "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f4"
  ],
  top2: [
    "top2",
    "right2",
    "title2",
    "left2",
    "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a2"
  ],
  right2: ["right2", "title2"],
  title2: ["title2"],
  left2: [
    "left2",
    "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a2"
  ],
  دکمهیرزروسایت2: [
    "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a2"
  ],
  details2: [
    "details2",
    "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f2",
    "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f4"
  ],
  رزروجدید2: ["\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f2"],
  رزروجدید4: ["\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f4"],
  دکمهروزورودمهمان: [
    "\u062f\u06a9\u0645\u0647\u0631\u0648\u0632\u0648\u0631\u0648\u062f\u0645\u0647\u0645\u0627\u0646",
    "top3",
    "right3",
    "title3",
    "left3",
    "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a3",
    "details3",
    "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f3",
    "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f5"
  ],
  top3: [
    "top3",
    "right3",
    "title3",
    "left3",
    "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a3"
  ],
  right3: ["right3", "title3"],
  title3: ["title3"],
  left3: [
    "left3",
    "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a3"
  ],
  دکمهیرزروسایت3: [
    "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a3"
  ],
  details3: [
    "details3",
    "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f3",
    "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f5"
  ],
  رزروجدید3: ["\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f3"],
  رزروجدید5: ["\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f5"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  httpRestApiFetcher: typeof DataFetcher;
  dontHave2: typeof Modal;
  header: "div";
  igAndT: "div";
  img: typeof PlasmicImg__;
  dontHave: "h3";
  des: "div";
  footer: "div";
  up: "div";
  right4: "div";
  telegram: "div";
  left4: "div";
  bale: "div";
  down: "div";
  button: typeof Button;
  دکمهرزروسایت: "div";
  top: "div";
  right: "div";
  title: "div";
  left: "div";
  دکمهیرزروسایت: typeof Switch;
  details: "div";
  تسویه: "div";
  تسویه2: "div";
  تسویه4: "div";
  دکمهرزرودستی: "div";
  top2: "div";
  right2: "div";
  title2: "div";
  left2: "div";
  دکمهیرزروسایت2: typeof Switch;
  details2: "div";
  رزروجدید2: "div";
  رزروجدید4: "div";
  دکمهروزورودمهمان: "div";
  top3: "div";
  right3: "div";
  title3: "div";
  left3: "div";
  دکمهیرزروسایت3: typeof Switch;
  details3: "div";
  رزروجدید3: "div";
  رزروجدید5: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSettingNotification__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSettingNotification__VariantsArgs;
    args?: PlasmicSettingNotification__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSettingNotification__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSettingNotification__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSettingNotification__ArgProps,
          internalVariantPropNames: PlasmicSettingNotification__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSettingNotification__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSettingNotification";
  } else {
    func.displayName = `PlasmicSettingNotification.${nodeName}`;
  }
  return func;
}

export const PlasmicSettingNotification = Object.assign(
  // Top-level PlasmicSettingNotification renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    httpRestApiFetcher: makeNodeComponent("httpRestApiFetcher"),
    dontHave2: makeNodeComponent("dontHave2"),
    header: makeNodeComponent("header"),
    igAndT: makeNodeComponent("igAndT"),
    img: makeNodeComponent("img"),
    dontHave: makeNodeComponent("dontHave"),
    des: makeNodeComponent("des"),
    footer: makeNodeComponent("footer"),
    up: makeNodeComponent("up"),
    right4: makeNodeComponent("right4"),
    telegram: makeNodeComponent("telegram"),
    left4: makeNodeComponent("left4"),
    bale: makeNodeComponent("bale"),
    down: makeNodeComponent("down"),
    button: makeNodeComponent("button"),
    دکمهرزروسایت: makeNodeComponent(
      "\u062f\u06a9\u0645\u0647\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a"
    ),
    top: makeNodeComponent("top"),
    right: makeNodeComponent("right"),
    title: makeNodeComponent("title"),
    left: makeNodeComponent("left"),
    دکمهیرزروسایت: makeNodeComponent(
      "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a"
    ),
    details: makeNodeComponent("details"),
    تسویه: makeNodeComponent("\u062a\u0633\u0648\u06cc\u0647"),
    تسویه2: makeNodeComponent("\u062a\u0633\u0648\u06cc\u06472"),
    تسویه4: makeNodeComponent("\u062a\u0633\u0648\u06cc\u06474"),
    دکمهرزرودستی: makeNodeComponent(
      "\u062f\u06a9\u0645\u0647\u0631\u0632\u0631\u0648\u062f\u0633\u062a\u06cc"
    ),
    top2: makeNodeComponent("top2"),
    right2: makeNodeComponent("right2"),
    title2: makeNodeComponent("title2"),
    left2: makeNodeComponent("left2"),
    دکمهیرزروسایت2: makeNodeComponent(
      "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a2"
    ),
    details2: makeNodeComponent("details2"),
    رزروجدید2: makeNodeComponent(
      "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f2"
    ),
    رزروجدید4: makeNodeComponent(
      "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f4"
    ),
    دکمهروزورودمهمان: makeNodeComponent(
      "\u062f\u06a9\u0645\u0647\u0631\u0648\u0632\u0648\u0631\u0648\u062f\u0645\u0647\u0645\u0627\u0646"
    ),
    top3: makeNodeComponent("top3"),
    right3: makeNodeComponent("right3"),
    title3: makeNodeComponent("title3"),
    left3: makeNodeComponent("left3"),
    دکمهیرزروسایت3: makeNodeComponent(
      "\u062f\u06a9\u0645\u0647\u06cc\u0631\u0632\u0631\u0648\u0633\u0627\u06cc\u062a3"
    ),
    details3: makeNodeComponent("details3"),
    رزروجدید3: makeNodeComponent(
      "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f3"
    ),
    رزروجدید5: makeNodeComponent(
      "\u0631\u0632\u0631\u0648\u062c\u062f\u06cc\u062f5"
    ),

    // Metadata about props expected for PlasmicSettingNotification
    internalVariantProps: PlasmicSettingNotification__VariantProps,
    internalArgProps: PlasmicSettingNotification__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSettingNotification;
/* prettier-ignore-end */
