/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jyct5VPKPFiM97kWoWCufE

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantshlYb5KihnAh5 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: HlYb5kihnAh5/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantshlYb5KihnAh5
});
